name: Jekyll Build
description: Build the Jekyll site
runs:
  using: composite
  steps:
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.4"
        bundler-cache: true
    - run: ./j build
      shell: bash
